# @Author: xiaocao
# @Date:   2023-04-20 17:01:24
# @Last Modified by:   xiaocao
# @Last Modified time: 2023-04-20 17:08:09



name: ci

on:
  push:
    # branches: ['master', 'develop']
    # 这里注释掉，这里是或的关系
    tags: ["build-warp-*"]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image
        with:
          image: wdjoys/warp-proxy
          tags: v1, latest
          registry: docker.io
          dockerfile: warp/dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}